### PR TITLE
Add pod functionality

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
The final result
sub_pod 2

**Comment by KaitCrawford** [comment]
@justinvdm do you have suggestions on how to go about testing the directive?
@rudigiesler, @jpaidoussi this is ready for a first review. sorry for the size :(

**Comment by rudigiesler** [comment]
The code looks good to me. With the CSS though, is it possible to have more space before and after the dividing line? It seems strange to have space at the top and bottom of the box, but not to have the same amount of space before and after the line.

**Comment by KaitCrawford** [comment]
@rudigiesler here are the pods with added padding around the subscriptions
padded_pods

**Comment by rudigiesler** [comment]
:+1:

**Comment by KaitCrawford** [comment]
@justinvdm I've added the tests but I'm not sure how to run them. Does this repo need it's own `karma.conf.coffee` file or is there some other way to do it?

**Comment by KaitCrawford** [comment]
@justinvdm ready for review. I just need to move the angular JS files to somewhere more appropriate

**Comment by KaitCrawford** [comment]
Landing since @justinvdm is happy with the angular and @rudigiesler has :+1: 'd the rest

**Pull request merged**
